### ISSUE TITLE
empty attribute is removed

### ISSUE THREAD

**Issue by primavera133** [brunobertolini/gulp-directive-replace#13]
I have a template that needs to have an empty attribute, but it is being removed.

It is a case of ng-options, for a select box where I want to have a static option on top in case no model is selected yet. This option-tag needs to have value="" for angular to pick it up properly. See more over at the docs: https://docs.angularjs.org/api/ng/directive/select

So, is this optimisation of the html customizeable? Can I turn it off?

**Comment by brunobertolini** [comment]
This you resolve changing the minify options, more specifically the 'removeEmptyAttributes' option, according the [html-minifier docs](https://www.npmjs.com/package/html-minifier#options-quick-reference).

Try this:

```
directiveReplace({
    minify: {
        removeEmptyAttributes: false
    }
});
```
