### ISSUE TITLE
Fails when more than one `templateUrl` instance per file

### ISSUE THREAD

**Issue by mpiasta-ca** [brunobertolini/gulp-directive-replace#7]
(1) If a file has more than one `templateUrl: '.../template.html';` instance, the script fails and is unable to inline both templates properly. This could be the case if a user has more than one directive per file, or has a directive which references multiple template files.

Should upgrade the plugin logic to map the `templateUrl` matches to an array, then get template contents for each result in that array, then search-replace with `template: '...'` based on content position within that array.

(2) If using `<script type="text/ng-template" id="template.html">...</script>` to push a template into your `$templateCache`, when plugin comes across `templateUrl: 'template.html';` instance in a directive, it will fail to find a matching template file.

In this case, the expected behavior is to use `try { ... } catch (error) { ... }` so that the gulp task doesn't crash. And in the case that a template file is not found, skip replacing this instance and leave it as-is (ie. leave it as `templateUrl: 'template.html'`, instead of making it `template: ''` [where the content is blank]).

**Comment by marcelaraujo** [comment]
It's done.

**Comment by marcelaraujo** [comment]
@brunobertolini Can you close this issue please?
